version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ruler
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: codex
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ruler
      MINIO_ROOT_PASSWORD: 12345qwe
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  s3-init:
    image: minio/mc
    depends_on:
      - s3
    environment:
      MINIO_ROOT_USER: ruler
      MINIO_ROOT_PASSWORD: 12345qwe
      MINIO_BUCKET_NAME: vault
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set local http://s3:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do
        echo 'Waiting for MinIO to become available...';
        sleep 2;
      done;

      echo 'Creating bucket...';
      /usr/bin/mc mb local/$${MINIO_BUCKET_NAME};

      echo 'Making bucket public...';
      /usr/bin/mc anonymous set download local/$${MINIO_BUCKET_NAME};

      echo 'MinIO init done.';
      "

  gateway:
    build:
      context: ./services/gateway-service
      target: dev
    depends_on:
      - codex
      - vault
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CODEX_SERVICE_URL: "http://codex:3001"
      VAULT_SERVICE_URL: "http://vault:3002"
    volumes:
      - ./services/gateway-service:/app
  
  codex:
    build:
      context: ./services/codex-service
      target: dev
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: "postgresql://ruler:123qwe@db:5432/codex"
    volumes:
      - ./services/codex-service:/app

  vault:
    build:
      context: ./services/vault-service
      target: dev
    depends_on:
      - s3
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      PUBLIC_ENDPOINT: http://localhost:9000
      S3_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY: ruler
      S3_SECRET_KEY: 12345qwe
      S3_BUCKET: vault
      S3_REGION: default
    volumes:
      - ./services/vault-service:/app

  council:
    build:
      context: ./apps/council-web
      target: dev
    depends_on:
      - codex
    ports:
      - "5175:5175"
    environment:
      PORT: 5175
      GATEWAY_URL: http://gateway:3000
    volumes:
      - ./apps/council-web:/app

volumes:
  postgres_data:
  minio_data:
