packages:
  - apps/*
  - realms/*
  - packages/*
  - tools/*

nodeLinker: hoisted
autoInstallPeers: true

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
