archive:
  path: ../../docs

protocols:
  roadmap:
    prefix: Roadmap
    idDigits: 2
    path: ./roadmaps
    template: roadmap.nj
    aliases: ['roadmaps']
    fields:
      status:
        name: Status
        type: enum
        values: ['In progress', 'Done', 'Cancelled']
      created:
        name: Created
        type: date

  milestone:
    prefix: Milestone
    idDigits: 3
    path: ./milestones
    template: milestone.nj
    aliases: ['milestones']
    fields:
      status:
        name: Status
        type: enum
        values: ['In progress', 'Done', 'Cancelled']
      parent:
        name: Roadmap
        type: link
        protocol: roadmap
      created:
        name: Created
        type: date

  task:
    prefix: DOD
    idDigits: 4
    path: ./tasks
    template: task.nj
    aliases: ['tasks']
    fields:
      status:
        name: Status
        type: enum
        values: ['In progress', 'Done', 'Cancelled']
      parent:
        name: Milestone
        type: link
        protocol: milestone
      created:
        name: Created
        type: date

  idea:
    prefix: Idea
    idDigits: 3
    path: ./ideas
    template: idea.nj
    aliases: ['ideas']
    fields:
      created:
        name: Created
        type: date

logging:
  level: info
